import { useCallback, useEffect, useRef, useState } from "react";
import { fetchResult, fetchStatus, uploadPdf } from "./api/client";
import type { MemoResult, StatusResponse } from "./api/types";
import { ApiError } from "./api/types";
import { JobStatus } from "./components/JobStatus";
import { MemoViewer } from "./components/MemoViewer";
import { ObservabilityPanel } from "./components/ObservabilityPanel";
import { UploadPanel } from "./components/UploadPanel";
import styles from "./App.module.css";

type Phase = "idle" | "uploading" | "polling" | "complete" | "error";

export function App() {
  const [phase, setPhase] = useState<Phase>("idle");
  const [jobId, setJobId] = useState<string | null>(null);
  const [statusData, setStatusData] = useState<StatusResponse | null>(null);
  const [result, setResult] = useState<MemoResult | null>(null);
  const [errorMsg, setErrorMsg] = useState<string | null>(null);
  const intervalRef = useRef<ReturnType<typeof setInterval> | null>(null);

  // Clear polling interval on unmount
  useEffect(() => {
    return () => {
      if (intervalRef.current) clearInterval(intervalRef.current);
    };
  }, []);

  // Start polling when we have a job ID
  useEffect(() => {
    if (phase !== "polling" || !jobId) return;

    async function poll() {
      if (!jobId) return;
      try {
        const s = await fetchStatus(jobId);
        setStatusData(s);

        if (s.status === "complete") {
          if (intervalRef.current) clearInterval(intervalRef.current);
          const r = await fetchResult(jobId);
          setResult(r);
          setPhase("complete");
        } else if (s.status === "failed") {
          if (intervalRef.current) clearInterval(intervalRef.current);
          setErrorMsg(s.error ?? "Pipeline failed — check server logs.");
          setPhase("error");
        }
      } catch (err) {
        if (intervalRef.current) clearInterval(intervalRef.current);
        setErrorMsg(err instanceof ApiError ? err.message : String(err));
        setPhase("error");
      }
    }

    poll(); // immediate first poll
    intervalRef.current = setInterval(poll, 2000);

    return () => {
      if (intervalRef.current) clearInterval(intervalRef.current);
    };
  }, [phase, jobId]);

  const handleUpload = useCallback(async (file: File) => {
    setPhase("uploading");
    setErrorMsg(null);
    setResult(null);
    setStatusData(null);

    try {
      const { job_id } = await uploadPdf(file);
      setJobId(job_id);
      setPhase("polling");
    } catch (err) {
      setErrorMsg(err instanceof ApiError ? err.message : String(err));
      setPhase("error");
    }
  }, []);

  function handleReset() {
    if (intervalRef.current) clearInterval(intervalRef.current);
    setPhase("idle");
    setJobId(null);
    setStatusData(null);
    setResult(null);
    setErrorMsg(null);
  }

  return (
    <div className={styles.root}>
      <header className={styles.header}>
        <div className={styles.headerInner}>
          <div className={styles.logo}>
            <span className={styles.logoMark}>◈</span>
            <span className={styles.logoText}>DealFlow Agent</span>
          </div>
          <span className={styles.badge}>Multi-Agent AI · CRE Analysis</span>
        </div>
      </header>

      <main className={styles.main}>
        {/* Upload panel — shown while idle or uploading */}
        {(phase === "idle" || phase === "uploading") && (
          <UploadPanel
            onUpload={handleUpload}
            isUploading={phase === "uploading"}
          />
        )}

        {/* Error state */}
        {phase === "error" && (
          <div className={styles.errorCard}>
            <h3 className={styles.errorTitle}>Analysis Failed</h3>
            <p className={styles.errorBody}>{errorMsg}</p>
            <button className={styles.resetBtn} onClick={handleReset}>
              Try Again
            </button>
          </div>
        )}

        {/* Polling status */}
        {phase === "polling" && statusData && (
          <JobStatus status={statusData} />
        )}

        {/* Pipeline initializing (before first status response) */}
        {phase === "polling" && !statusData && (
          <div className={styles.initMsg}>Connecting to pipeline…</div>
        )}

        {/* Results */}
        {phase === "complete" && result && result.memo && (
          <div className={styles.results}>
            <div className={styles.resultsHeader}>
              <div>
                <h2 className={styles.resultsTitle}>Investment Memo</h2>
                <p className={styles.resultsSubtitle}>
                  Generated by DealFlow Agent · Job{" "}
                  <code>{result.job_id.slice(0, 8)}</code>
                </p>
              </div>
              <button className={styles.resetBtn} onClick={handleReset}>
                Analyze Another Deal
              </button>
            </div>

            <div className={styles.memoCard}>
              <MemoViewer memo={result.memo} riskScores={result.risk_scores} />
            </div>

            <ObservabilityPanel result={result} />
          </div>
        )}
      </main>
    </div>
  );
}
